### ISSUE TITLE
cannot create XpubDerivable from a non-hardened derivation path

### ISSUE THREAD

**Issue by nicbus** [BP-WG/bp-std#16]
Trying to build a `XpubDerivable` (to then build a `RgbDescr`) I get the
following error:
```
DerivationPath(InvalidIndex("84/1/0", HardenedRequired("84")))
```

Using RGB v0.10 there was no problem using a normal (non-hardened) derivation path.
Why is it not supported by `bp-std`/`derive`?

**Comment by dr-orlovsky** [comment]
Since it is a non-standard (and insecure) to use non-hardened derivation path

**Comment by dr-orlovsky** [comment]
@nicbus can I close this issue?

**Comment by nicbus** [comment]
it makes sense to me, thanks for the clarification
